### ISSUE TITLE
Google Test dependencies fail to compile with Visual Studio 15.8.2 2017

### ISSUE THREAD

**Issue by pauljurczak** [xtensor-stack/xtl#110]
Google Test is using `tr1` namespace, which is deprecated and doesn't compile. Google test projects compile with `_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING` defined, but there are linking problems for test_* projects.

**Comment by SylvainCorlay** [comment]
Sorry for the late reply. Did you use a pre-built gtest or enabled the build of gtest with `-D DOWNLOAD_GTEST=ON`?

**Comment by SylvainCorlay** [comment]
If you do the latter, gtest should be built with the same runtime and compiler settings as the main project.

**Comment by pauljurczak** [comment]
I don't remember that detail - I ended up using `xtl` without gtest. I will try the next release someday with the settings you recommended.

**Comment by JohanMabille** [comment]
We have upgraded to gtest 1.10, this should be fixed.
