### ISSUE TITLE
ARCH_INDEPENDENT is not available in CMake 3.13 and earlier.

### ISSUE THREAD

**Issue by krivenko** [xtensor-stack/xtl#225]
After the recent merge of #223, `xtl` fails to install in one of my CI environments based on Ubuntu Xenial. The issue is with the `ARCH_INDEPENDENT` keyword of the `write_basic_package_version_file()` macro, which was introduced only in [CMake v3.14](https://cmake.org/cmake/help/v3.14/release/3.14.html?highlight=arch_independent).

If you insist on using this fairly new feature, please, adjust the required CMake version. Thanks in advance!

**Comment by JohanMabille** [comment]
Sorry for the inconvenience, I didn't notice this feature was that recent.
